# L'outil mapme.biodiversity

## Démarche

Le package [*mapme.biodiversity*](https://mapme-initiative.github.io/mapme.biodiversity/index.html) facilite l'analyse statistique de la biodiversité ou d'autres politiques et projets spatialisés. Il propose divers indicateurs pour évaluer la préservation de l'environnement et les activités humaines. Le package est conçu pour permettre des extensions futures grâce à des ressources et des indicateurs personnalisés.

Le package fournit une interface unifiée pour télécharger et analyser différents jeux de données spatiales, gérant la complexité liée aux divers formats. Il simplifie l'accès aux données en interagissant avec plusieurs backends utilisés par les organisations qui distribuent ces données. Les utilisateurs peuvent contrôler l'analyse en sélectionnant les indicateurs à calculer, permettant ainsi un ajustement précis des processus.

Pour commencer, les utilisateurs saisissent un objet sf contenant uniquement des géométries de type polygone. Le package télécharge ensuite les données raster et vecteur spatiales et temporelles nécessaires correspondant à l'étendue du portefeuille. Les résultats sont ajoutés sous forme de colonnes de listes imbriquées dans l'objet portefeuille, permettant une utilisation aisée d'une large gamme d'indicateurs dans R.

Le processus d'utilisation est le suivant :

```{r diagram_mapme}
library(DiagrammeR) # Package R pour produire des diagrammes Mermaid

#| fig-cap: "Processus de traitement avec mapme.biodiversity"

mermaid("
graph TB
    AA(Définition des polygones d'analyse)
    A(Initialisation du portefeuille)
    B(Acquisition des ressources)
    C(Calcul des indicateurs)
    D(Analyse statistique avec R)
    E(Export vers QGIS ou autre)
    AA-->A
    A-->B
    B-->C
    C-->D
    C-->E
")
```