project:
  type: book
  output-dir: docs

book:
  site-url: https://betsaka.github.io/impact_training_mapme/
  title: "mapme_impact_training"
  author: "Florent Bédécarrats"
  date: "10/07/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - bases_R.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
