project:
  type: book
  output-dir: docs

book:
  site-url: https://betsaka.github.io/impact_training_mapme/
  title: "Evaluation d'impact de politiques et projets spatialisés"
  subtitle: "Théorie et pratiques sur les aires protégées malgache avec Mapme"
  author: "Florent Bédécarrats"
  repo-url: https://github.com/BETSAKA/mapme_impact_training
  cover-image: figures/IRD_010664_ORI_small.png
  cover-image-alt: "Déforestation à Madagascar © IRD - Bernard Moizo"
  date: "10/07/2024"
  chapters:
    - index.qmd
    - 01_programme.qmd
    - 02_introduction.qmd
    - bases_R.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true

execute:
  warning: false
  error: false
