project:
  type: book
  output-dir: docs

book:
  site-url: https://betsaka.github.io/impact_training_mapme/
  title: "Evaluation d'impact de politiques et projets"
  subtitle: "Formation théorique et application pratique sur les aires protégées à Madagascar"
  author: "Florent Bédécarrats"
  repo-url: https://github.com/BETSAKA/mapme_impact_training
  cover-image: figs/IRD_010664_ORI_small_title_copyright.png
  cover-image-alt: "Déforestation à Madagascar © IRD - Bernard Moizo"
  date: "10/09/2024"
  chapters:
    - index.qmd
    - 01_programme.qmd
    - 02_introduction.qmd
    - 03_data_preparation.qmd
    - bases_R.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true

execute:
  warning: false
  error: false
